# SPDX-License-Identifier: MIT
---

- name: Ensure graphing service is configured with datasources
  template:
    src: grafana-pcp-datasources.yaml.j2
    dest: "{{ __metrics_grafana_provisioning_path }}/datasources/grafana-pcp.yaml"
    mode: 0644
  become: yes
  notify: restart grafana

- name: Ensure graphing service is running and enabled on boot
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Ensure graphing service runtime settings are configured
  uri:
    url: "http://{{ __metrics_grafana_user }}:{{ __metrics_grafana_password }}@{{\
      \ __metrics_grafana_server }}/api/plugins/performancecopilot-pcp-app/settings"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    method: POST
    src: files/grafana-pcp-settings.json
