---
- name: Check whether key exists
  stat: path="{{ kdump_sshkey }}"
  register: sshkey_stats

- name: Create key
  command: "/usr/bin/ssh-keygen -t rsa -f {{ kdump_sshkey }} -N '' "
  when: not sshkey_stats.stat.exists

- name: Fetch key
  slurp:
    src: "{{ kdump_sshkey }}.pub"
  register: keydata

- name: Add key to authorized keys
  authorized_key:
    user: "{{ kdump_ssh_user }}"
    key: "{{ keydata.content|b64decode }}"
    state: present
  delegate_to: "{{ kdump_ssh_server }}"
