---
- hosts: all

  vars:
    certificate_requests:
      - name: mycert
        dns: www.example.com
        principal: HTTP/www.example.com@EXAMPLE.com
        ca: self-sign

  roles:
    - fedora.system_roles.certificate
