# SPDX-License-Identifier: MIT
---

- name: Setup metric collection service
  vars:
    pcp_pmlogger_discard: "{{ metrics_retention_days }}"
    pcp_target_hosts: "{{ metrics_monitored_hosts }}"
    pcp_rest_api: "{{ metrics_query_service|d(false)|bool or metrics_graph_service|d(false)|bool }}"
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_pcp"
  when: metrics_provider == 'pcp'

- name: Setup metric querying service
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_redis"
  when: metrics_query_service|d(false)|bool

- name: Setup metric graphing service
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_grafana"
  when: metrics_graph_service|d(false)|bool

- name: Setup Elasticsearch metrics
  vars:
    elasticsearch_agent: "{{ metrics_from_elasticsearch|d(false)|bool }}"
    elasticsearch_export_type: "{{ metrics_provider }}-{{ role_name }}"
    elasticsearch_export_index: "{{ metrics_provider }}"
    elasticsearch_export_metrics: "{{ metrics_into_elasticsearch|d(false)|bool }}"
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_elasticsearch"
  when: metrics_from_elasticsearch|d(false)|bool or metrics_into_elasticsearch|d(false)|bool

- name: Setup SQL Server metrics
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_mssql"
  when: metrics_from_mssql|d(false)|bool

- name: Setup bpftrace metrics
  vars:
    bpftrace_users:
      - {user: "{{ metrics_username }}", sasluser: "{{ metrics_username }}", saslpassword: "{{ metrics_password }}"}
  include_role:
    name: "redhat.rhel_system_roles.performancecopilot_metrics_bpftrace"
  when: metrics_from_bpftrace|d(false)|bool
