---
galaxy_info:
  author: Kirill Gliebov
  description: A role to configure terminal session recording
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
    - name: Fedora
      versions:
        - 31
        - 32
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - session
    - recording
    - tlog
    - redhat
    - fedora
    - centos
    - rhel

dependencies: []
