# SPDX-License-Identifier: MIT
---

- name: Set platform/version specific variables
  include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts['os_family'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ role_path }}/vars/{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  when: item is file

- name: Install Grafana packages
  package:
    name: "{{ __grafana_packages + __grafana_packages_extra }}"
    state: present

- name: Template Grafana configuration
  template:
    src: grafana.ini.j2
    dest: "{{ __grafana_conf }}"
    mode: 0640
  become: yes
  notify: restart grafana

- name: Ensure Grafana service is configured with datasources
  template:
    src: grafana-pcp-datasources.yaml.j2
    dest: "{{ __grafana_provisioning_path }}/datasources/grafana-pcp.yaml"

    mode: 0644
  become: yes
  notify: restart grafana

- name: Ensure graphing service is running and enabled on boot
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Ensure graphing service runtime settings are configured
  uri:
    url: "http://{{ __grafana_user }}:{{ __grafana_password }}@{{ __grafana_server }}/api/plugins/performancecopilot-pcp-app/settings"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    method: POST
    src: files/grafana-pcp-settings.json
