# SPDX-License-Identifier: MIT
---
# Default metrics provider is PCP
metrics_provider: pcp

# Number of days of historical performance data to keep.
metrics_retention_days: 7

# List of remote hosts to be analysed by the target host.
# These hosts will have metrics recorded (for historical
# analysis) and automated rule inference (for alerting).
metrics_monitored_hosts: []

# Provide a scalable query language (using Redis) and the
# PMWEBAPI(3) REST API for metrics at localhost:44322
# OpenMetrics endpoint at localhost:44322/metrics
metrics_query_service: no

# Provide a Graphing server (Grafana) with enabled plugins
# for the available metrics services.
# Graphing service at localhost:3000
metrics_graph_service: no
